### PR TITLE
Chirp feature/felix/bamboo 69/dark mode

### PR DESCRIPTION
**Pull request by jsczzzx**
- Added theme.service in shared to implement light mode and dark mode
- Added ./themes/lara-dark-indigo.sass and ./themes/lara-light-indigo.sass.
- Refactors navbar to fit dark mode
- Some other style refactors to get unified theme style: all buttons to p-button, font setting in styles.sass and more.

Screenshot 2024-05-05 124516
Screenshot 2024-05-05 124624
Screenshot 2024-05-05 124649
Screenshot 2024-05-05 124701

### CODE REVIEW

**Review by mercuryedge117 — COMMENTED** [review]
Good work, but I still have some suggestion about what could be improved
- we could have a dark mode icon / blank filled icon for our Red Panda Icon on pages and navbar
- all the windows component didn't apply changes with dark mode theme, and cause some issue with their close button
QQ截图20240505133133
QQ截图20240505133207

**Review by mercuryedge117 — COMMENTED** [review]
Please change the change password window component as well
image
Everything else looks good

**Comment by jsczzzx** [comment]
- New logo added, change the color to match our project.
- Redesign password, login and register windows to use dark theme.
- Use localStorage to save the theme selection locally.

**Review by mercuryedge117 — COMMENTED** [review]
reverted register button

**Review by mercuryedge117 — APPROVED** [review]
Perfect work, thanks

**Pull request merged**
