### PR TITLE
Chirp feature/yuri/bamboo 54/bind edit profile input fields

### PR DESCRIPTION
**Pull request by YueyingCoding**

### CODE REVIEW

**Comment by YueyingCoding** [comment]
1. Redo edit profile window to make it match with the user model
2. Update the html thus is converted to a reactive form
3. Current User is hardcoded in user.service.ts, will be updated to fetch data from backend
4. Bind the form
5. Using onSubmit function to update the info for current user, need a post service to update in the database in the future
6. Add proper close by clicking on the "Confirm" button

**Review by mercuryedge117 — COMMENTED** [review]
- Please add some label for failed validators to notice user what they should do
- Also, for each input, add some label to tell user which input field belong to what info

**Review by mercuryedge117 — COMMENTED** [review]
- User-info component didn't have to use optional variables as warning showed
622738ed608b7db09893a05da45c77d

- Please add age and phone section to user-info (profile) page

**Review by mercuryedge117 — APPROVED** [review]
Looks great!
I prefer original style more, but I will do it when refactor period is coming

**Pull request merged**
