### PR TITLE
Chirp feature/felix/bamboo 91/admin layout

### PR DESCRIPTION
**Pull request by jsczzzx**
- Responsive design for admin page
- Fit admin page to dark mode
- Some other layout improvements

ezgif-1-86f88eb92c

### CODE REVIEW

**Comment by Jingyued** [comment]
three minor suggestions you may consider
1. fix the gap
Screenshot 2024-05-09 at 10 56 16 PM

2. remove this on the bottom bar or make it longer
Screenshot 2024-05-09 at 10 55 43 PM

3. change the background color to #5f5f5f in dark mode like this to satisfy the contrast accessibility requirements
Screenshot 2024-05-09 at 10 52 51 PM
Screenshot 2024-05-09 at 10 54 59 PM

**Comment by Jingyued** [comment]
overall fancy work!

**Comment by jsczzzx** [comment]
> three minor suggestions you may consider
> 
> 1. fix the gap
> 
> Screenshot 2024-05-09 at 10 56 16 PM
> 2. remove this on the bottom bar or make it longer
> 
> Screenshot 2024-05-09 at 10 55 43 PM
> 3. change the background color to #5f5f5f in dark mode like this to satisfy the contrast accessibility requirements
> 
> Screenshot 2024-05-09 at 10 52 51 PM Screenshot 2024-05-09 at 10 54 59 PM

**Review by Jingyued — APPROVED** [review]
works well on my side

**Pull request merged**
